### ISSUE TITLE
Undefined array key "CurrentInputMode" in PlayerSession at line 50 (I am using api 4.2.6)

### ISSUE THREAD

**Issue by Swedeachu** [sylvrs/PlayerTags#20]
**THIS ONLY HAPPENED WHEN I WAS USING FAKE PLAYERS PLUG IN**
[Server thread/CRITICAL]: ErrorException: "Undefined array key "CurrentInputMode"" (EXCEPTION) in "plugins/PlayerTags.phar/src/sys/jordan/tags/session/PlayerSession" at line 50
--- Stack trace ---
  #0 plugins/PlayerTags.phar/src/sys/jordan/tags/session/PlayerSession(50): pocketmine\errorhandler\ErrorToExceptionHandler::handle(integer 2, string[38] Undefined array key "CurrentInputMode", string[111] phar://C:/Users/camde/Desktop/swim server/plugins/PlayerTags.phar/src/sys/jordan, integer 50)
  #1 plugins/PlayerTags.phar/src/sys/jordan/tags/session/SessionManager(27): sys\jordan\tags\session\PlayerSession::create(object pocketmine\player\Player#105826)
  #2 plugins/PlayerTags.phar/src/sys/jordan/tags/PlayerTagsListener(59): sys\jordan\tags\session\SessionManager->get(object pocketmine\player\Player#105826)
  #3 pmsrc/src/event/RegisteredListener(75): sys\jordan\tags\PlayerTagsListener->handleDataPacketReceive(object pocketmine\event\server\DataPacketReceiveEvent#104972)
  #4 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent#104972)
  #5 pmsrc/src/network/mcpe/NetworkSession(396): pocketmine\event\Event->call()
  #6 plugins/FakePlayer-master/src/muqsit/fakeplayer/DefaultFakePlayerListener(50): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#104882, string[2] q.)
  #7 pmsrc/src/scheduler/ClosureTask(63): muqsit\fakeplayer\DefaultFakePlayerListener::muqsit\fakeplayer\{closure}()
  #8 pmsrc/src/scheduler/TaskHandler(117): pocketmine\scheduler\ClosureTask->onRun()
  #9 pmsrc/src/scheduler/TaskScheduler(144): pocketmine\scheduler\TaskHandler->run()
  #10 pmsrc/src/plugin/PluginManager(467): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 92)
  #11 pmsrc/src/Server(1768): pocketmine\plugin\PluginManager->tickSchedulers(integer 92)
  #12 pmsrc/src/Server(1657): pocketmine\Server->tick()
  #13 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #14 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[35] C:\Users\camde\Desktop\swim server\, string[43] C:\Users\camde\Desktop\swim server\plugins\)
  #15 pmsrc/src/PocketMine(327): pocketmine\server()
  #16 pmsrc(11): require(string[79] phar://C:/Users/camde/Desktop/swim server/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by sylvrs** [comment]
I've messaged @Muqsit about this, but my assumption is that FakePlayer doesn't send this sort of data. Until I can get any further information, this isn't an issue with this plugin.
