### ISSUE TITLE
Lag problem

### ISSUE THREAD

**Issue by mikeygio10** [sylvrs/PlayerTags#3]
Every time it updates my cpu goes to 100%

**Comment by sylvrs** [comment]
This does not utilize a ton of resources, so before I can decipher what is happening, I'll need a few things:

1. Your CPU
2. The amount of RAM you have
3. Your plugin configuration (it can be located under PlayerTags/config.yml)
4. Timings (Run /timings on, let it run for a couple of minutes and then run /timings paste & give me the URL it outputs)

**Comment by mikeygio10** [comment]
i7 Intel
2gig
Ugh I removed but I can try to add back
https://timings.pmmp.io/?id=36755

**Comment by sylvrs** [comment]
This issue is not caused by my plugin. Looking at your timings, your machine is having issues.

My timings comparatively have no issues *whatsoever*: https://timings.pmmp.io/?id=36891

**Comment by mikeygio10** [comment]
I took it onto a blank server with no plugins brand new and it does the same thing.

**Comment by sylvrs** [comment]
Testing with multiple machines and multiple people, I can tell you that your machine is having issues. Unless I know your plugin configuration, your PocketMine version, and the exact specifications of your computer, I can’t help
