### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by iAtomPlaza** [sylvrs/PlayerTags#6]
Server crash when i join server, have tag set to {health_bar} in config
https://crash.pmmp.io/view/4383522

**Comment by sylvrs** [comment]
Seems to be an issue w/ PiggyFactions. I'd suggest removing it from your config, if it's set.

**Comment by iAtomPlaza** [comment]
> Seems to be an issue w/ PiggyFactions. I'd suggest removing it from your config, if it's set.

crashes with anything in config, i have to leave the config an empty string to prevent crashing...

**Comment by sylvrs** [comment]
Yes, I'll be deploying a fix for PiggyFactions soon. Thank you for reporting!

**Comment by iAtomPlaza** [comment]
ill be waiting!
