### ISSUE TITLE
Suggestion: Add friend status tags / afk message by UserManager plugin

### ISSUE THREAD

**Issue by thebigsmileXD** [sylvrs/PlayerTags#7]
I might even PR this
https://github.com/thebigsmileXD/UserManager
Would be cool to see {nickname}, {bio} and if you are friends with a person

**Comment by sylvrs** [comment]
Of course! This seems like a really cool plugin to integrate. If you'd like to implement it for full satisfaction on your end, I'd be glad to review it. Otherwise, I'll implement it myself.

**Comment by thebigsmileXD** [comment]
Hm, just thought about it:
Why not release a virion that any plugin can implement, containing
registerPrefix() (i.e. plugin name) and registerTag()
so you don't have to care about the code and plugin devs have an API to just add it? The same api could then be integrated into i.e. ScoreboardAPI, BossAnnouncement, Texter - basically anything that uses `{tag}` in their code
