### ISSUE TITLE
Disconnects when happen a reload

### ISSUE THREAD

**Issue by IvanCraft623** [sylvrs/PlayerTags#8]
When i relaod the server it disconect all the players online showing the message: "Invalid session detected. Please join back to validate your session"
![imagen](https://user-images.githubusercontent.com/57236932/89237021-c50e4680-d5b7-11ea-8d7a-3aa790f61942.png)

**Comment by sylvrs** [comment]
Yes, this is a necessary step to avoid the plugin from crashing since it can't retain the player's OS / input mode during a reload.
